POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Cecilia1",
  "email": "Cecilia1@test.com",
  "password": "123456"
}

###
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "Cecilia1@test.com",
  "password": "123456"
}

###
POST http://localhost:8080/services
Content-Type: application/json
Authorization: Bearer DIN_TOKEN_HÄR


{
  "title": "Handla",
  "description": "Handla mat",
  "price": 300
}

###
GET http://localhost:8080/services
Authorization: Bearer DIN_TOKEN_HÄR

